development:
  adapter: redis
  url: redis://redis_container:6379/1

test:
  adapter: test

production:
  adapter: redis
  url: redis://redis_container:6379/1
  channel_prefix: delivery_service_production
